name: Uni
favicon: null
layout_spectrum: 0.4080840484239161
typography_spectrum: 0.8718491811305285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4132681854534894
  lightness: 0.2055923189036548
  saturation: 0.7511248721275479
  rhythmicContrast: 0.6400148991961032
purpose: []
